services:
  web:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    user: 1000:1000
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8880
      is_main: true
x-runtipi:
  schema_version: 2
