services:
  web:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.7.2@sha256:fa52dce920c3610c78fccde4f6fa064fb092ae95018cf42b42d84d876655e8d9
    user: 1000:1000
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8880
      is_main: true
x-runtipi:
  schema_version: 2
