services:
  web:
    image: savewithstash/stash:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 5173
    volumes:
    - ${APP_DATA_DIR}/data/app:/app/data
    - ${APP_DATA_DIR}/data/models:/app/models
    x-runtipi:
      internal_port: 5173
      is_main: true
x-runtipi:
  schema_version: 2
