services:
  web:
    image: flomp/wanderer-web:latest
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ORIGIN: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_DISABLE_SIGNUP: 'false'
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER: admin
      UPLOAD_PASSWORD: ${APP_PASSWORD}
      VALHALLA_URL: https://valhalla1.openstreetmap.de
      NOMINATIM_URL: https://nominatim.openstreetmap.org
      OVERPASS_API_URL: https://overpass-api.de
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${APP_SEED}
    volumes:
    - ${APP_DATA_DIR}/data/uploads:/app/uploads
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
  search:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${APP_SEED}
    volumes:
    - ${APP_DATA_DIR}/data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
    labels:
    - runtipi.managed=true
  db:
    image: flomp/wanderer-db:latest
    depends_on:
      search:
        condition: service_healthy
    environment:
      POCKETBASE_ENCRYPTION_KEY: ${APP_WANDERER_ENCRYPTION_KEY}
      MEILI_URL: http://search:7700
      MEILI_MASTER_KEY: ${APP_SEED}
      ORIGIN: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/pb_data:/pb_data
    - ${APP_DATA_DIR}/data/plugins:/data/plugins
    healthcheck:
      test:
      - CMD
      - /curl
      - --fail
      - http://localhost:8090/health
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
