services:
  server:
    image: quay.io/jupyter/base-notebook:lab-4.6.2@sha256:50d8c29bb555af7ba18e956c97734c31ada26ee12d7e6dc77927608cb730d108
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token=${APP_PASSWORD}
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8888
      is_main: true
x-runtipi:
  schema_version: 2
