services:
  server:
    image: quay.io/jupyter/base-notebook:latest
    volumes:
    - ${APP_DATA_DIR}/data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token=${APP_PASSWORD}
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8888
      is_main: true
x-runtipi:
  schema_version: 2
