services:
  server:
    image: quay.io/jupyter/base-notebook:latest
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token=${APP_PASSWORD}
    restart: on-failure
    x-runtipi:
      internal_port: 8888
      is_main: true
x-runtipi:
  schema_version: 2
