services:
  web:
    image: dumbwareio/dumbpad:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data:/app/data
    environment:
      SITE_TITLE: DumbPad
      BASE_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
