services:
  web:
    image: ghcr.io/music-assistant/server:2.9.13@sha256:5ded610a2804fb7a973d2cbe390df09ceb67f0d7f603bcacd21ebaaa5a8a9b62
    restart: unless-stopped
    user: 1000:1000
    network_mode: host
    volumes:
    - ${APP_DATA_DIR}/data:/data/
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/media
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    security_opt:
    - apparmor=unconfined
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8896
      is_main: true
x-runtipi:
  schema_version: 2
