services:
  server:
    image: zoraxydocker/zoraxy:latest
    restart: unless-stopped
    ports:
    - 41080:80
    - 41443:443
    volumes:
    - ${APP_DATA_DIR}/data/config/:/opt/zoraxy/config
    - /etc/localtime:/etc/localtime:ro
    environment:
      FASTGEOIP: 'false'
      ZEROTIER: 'false'
      DOCKER: 'false'
      NOAUTH: 'true'
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
