services:
  init_perms:
    image: encryptedenergy/ee-gateway-worker:latest
    user: 0:0
    entrypoint:
    - sh
    - -c
    - chown -R 1000:1000 /data
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data:/data
  ui:
    image: encryptedenergy/ee-gateway-ui:latest
    init: true
    restart: on-failure
    depends_on:
      init_perms:
        condition: service_completed_successfully
    volumes:
    - ${APP_DATA_DIR}/data:/data
    environment:
      EE_DATA_DIR: /data
      EE_UI_PORT: 8080
      EE_GATEWAY_VERSION: 0.10.7
    x-runtipi:
      internal_port: 8080
      is_main: true
  worker:
    image: encryptedenergy/ee-gateway-worker:latest
    init: true
    restart: on-failure
    depends_on:
      init_perms:
        condition: service_completed_successfully
    network_mode: host
    cap_add:
    - NET_ADMIN
    - NET_RAW
    device_cgroup_rules:
    - c 188:* rwm
    - c 166:* rwm
    volumes:
    - ${APP_DATA_DIR}/data:/data
    - /var/run/dbus:/var/run/dbus:ro
    - /dev:/dev
    environment:
      EE_DATA_DIR: /data
x-runtipi:
  schema_version: 2
