services:
  app:
    image: lissy93/domain-locker:latest
    user: 1000:1000
    restart: on-failure
    environment:
      DL_ENV_TYPE: selfHosted
      DL_PG_HOST: domain-locker_postgres_1
      DL_PG_PORT: 5432
      DL_PG_USER: postgres
      DL_PG_PASSWORD: domain-locker
      DL_PG_NAME: domain_locker
    depends_on:
    - postgres
    healthcheck:
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:3000/api/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    x-runtipi:
      internal_port: 3000
      is_main: true
  postgres:
    image: postgres:latest
    user: 1000:1000
    restart: on-failure
    environment:
      POSTGRES_DB: domain_locker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: domain-locker
    volumes:
    - ${APP_DATA_DIR}/data/db_data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
x-runtipi:
  schema_version: 2
