services:
  web:
    image: uusec/openresty-manager:latest
    hostname: web
    restart: unless-stopped
    ports:
    - 3080:80
    - 3443:443
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${APP_DATA_DIR}/data/acme:/opt/om/acme
    - ${APP_DATA_DIR}/data/data:/opt/om/data
    - ${APP_DATA_DIR}/data/conf:/opt/om/nginx/conf
    - ${APP_DATA_DIR}/data/logs:/opt/om/nginx/logs
    environment:
    - OM_USE_HTTPS=no
    - NGINX_RESOLVER=resolver 127.0.0.11 valid=30s ipv6=off local=on;
    - PUID=1000
    - PGID=1000
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 34567
      is_main: true
x-runtipi:
  schema_version: 2
