services:
  app:
    image: ghcr.io/swingmx/swingmusic:v3.0.0@sha256:a49155d1809bc6ad09d87d76cc91648c149fc80146b5e10260e70fe1cfa78175
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/music:/music:rw
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/downloads
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 1970
      is_main: true
x-runtipi:
  schema_version: 2
