services:
  app:
    image: ghcr.io/swingmx/swingmusic:latest
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/music:/music:rw
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/downloads
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 1970
      is_main: true
x-runtipi:
  schema_version: 2
