services:
  server:
    image: voidic/route96:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/uploads:/app/data
    - ${APP_DATA_DIR}/data/config.yaml:/app/config.yaml
    environment:
      RUST_LOG: info
      APP_PUBLIC_URL: http://${APP_DOMAIN}:8002
    depends_on:
    - db
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8002
      is_main: true
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: moneyprintergobrrr
      MYSQL_USER: route96
      MYSQL_PASSWORD: moneyprintergobrrr
      MYSQL_DATABASE: route96
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
