services:
  web:
    image: ghcr.io/perber/leafwiki:v0.12.0@sha256:a4629aba418ddf6e70f8c9e1f723aff32b3715217cc1b8c3959a43ce2cf8fc2b
    restart: unless-stopped
    environment:
      LEAFWIKI_JWT_SECRET: ${APP_SEED}
      LEAFWIKI_ADMIN_PASSWORD: ${APP_PASSWORD}
      LEAFWIKI_ALLOW_INSECURE: 'true'
    volumes:
    - ${APP_DATA_DIR}/data:/app/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
