services:
  web:
    image: dennysubke/threema-web:v2.6.5@sha256:01f8b0ca6322f11579610b012c3440001743efb593dd845668a4e1f3d881e1a2
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
