services:
  server:
    image: linuxserver/snapdrop:latest
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
