services:
  web:
    image: ghcr.io/danvergara/morphos-server:latest
    restart: on-failure
    stop_grace_period: 1m
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
