services:
  app:
    image: akaunting/akaunting:latest
    restart: on-failure
    environment:
      AKAUNTING_SETUP: 'true'
      LOCALE: en-US
      DB_HOST: akaunting_db_1
      DB_PORT: 3306
      DB_NAME: akaunting
      DB_USERNAME: admin
      DB_PASSWORD: akaunting_password
      DB_PREFIX: asd_
      COMPANY_NAME: My Company
      COMPANY_EMAIL: my@company.com
      ADMIN_EMAIL: umbrel@umbrel.local
      ADMIN_PASSWORD: ${APP_PASSWORD}
    depends_on:
    - db
    x-runtipi:
      internal_port: 80
      is_main: true
  db:
    image: mariadb:latest
    user: 1000:1000
    restart: on-failure
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: admin
      MYSQL_PASSWORD: akaunting_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
    - ${APP_DATA_DIR}/db:/var/lib/mysql
x-runtipi:
  schema_version: 2
