services:
  web:
    image: ghcr.io/civilblur/mazanoke:v1.1.6@sha256:92cc7474deb789af6549318563b7a9ee750131f9f7b297cc9c87ab67e656c22c
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z 127.0.0.1 80 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
