services:
  importer:
    image: fireflyiii/data-importer:latest
    restart: on-failure
    environment:
    - FIREFLY_III_URL=http://firefly-iii_server_1:8080
    - VANITY_URL=http://localhost:30009
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
