services:
  deepsea:
    image: ghcr.io/retropex/custom-dashboard-ocean:v2.0.4@sha256:9f5b867d2c5873390614a5e7faab58a4279ecd451b47b2db0034308c35166970
    user: 1000:1000
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data:/app/data/
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
