services:
  app:
    image: ghcr.io/egzola/telegrapho:1.0.1@sha256:9486b185b993398cc651158a9292c2fa54eb83254c83d610759988fb20b413b8
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      PORT: 3712
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3712
      is_main: true
x-runtipi:
  schema_version: 2
