services:
  web:
    image: eduard256/strix:2.1.0@sha256:d34883001c2acf812446863281fe17a411cb16696f070d3fe4ae24b0be177ee5
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 4567
      is_main: true
x-runtipi:
  schema_version: 2
