services:
  web:
    image: eduard256/strix:latest
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 4567
      is_main: true
x-runtipi:
  schema_version: 2
