services:
  server:
    image: ghcr.io/lissy93/web-check:2.2.0@sha256:455bf61b5cb69b48e1ce600d05ad294fff5a1b8a60b361c54b4893edab6ec496
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data:/app/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
