services:
  web:
    image: vectorim/element-web:v1.12.25@sha256:ac50d4eebafd954d7d7e2887d4693bcc91c54c0d00546a3410eeae77e6b342d5
    user: nginx:nginx
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
