services:
  server:
    image: kyantech/palmr:latest
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      PALMR_UID: 1000
      PALMR_GID: 1000
    volumes:
    - ${APP_DATA_DIR}/data:/app/server
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 5487
      is_main: true
x-runtipi:
  schema_version: 2
