services:
  web:
    image: jc21/nginx-proxy-manager:2.15.1@sha256:52b2c59994f3d36acfcf70a1626f29734df0ed8c71bacc0269f78b6f939858bb
    hostname: web
    restart: unless-stopped
    ports:
    - 40080:80
    - 40443:443
    volumes:
    - ${APP_DATA_DIR}/data/npm-data:/data
    - ${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 81
      is_main: true
  docker-host:
    image: qoomon/docker-host:3.3.1@sha256:ec9d214d7fa88932e9186ca2f4419d44661376929931248525b08e7fa9e270f7
    hostname: localhost
    cap_add:
    - NET_ADMIN
    - NET_RAW
    restart: unless-stopped
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
