services:
  app:
    image: ghcr.io/coderamp-labs/gitingest:main
    restart: unless-stopped
    environment:
    - ALLOWED_HOSTS=localhost,localhost,${APP_GITINGEST_LOCAL_IPS}
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
