services:
  web:
    image: ghcr.io/karakeep-app/karakeep:latest
    user: 1000:1000
    restart: unless-stopped
    environment:
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: ${APP_SEED}
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${APP_SEED}
      NEXTAUTH_URL: http://localhost:8620
      KARAKEEP_VERSION: release
    volumes:
    - ${APP_DATA_DIR}/data/karakeep_data:/data
    depends_on:
    - chrome
    - meilisearch
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
  chrome:
    image: zenika/alpine-chrome:latest
    user: 1000:1000
    restart: unless-stopped
    command:
    - --no-sandbox
    - --disable-gpu
    - --disable-dev-shm-usage
    - --remote-debugging-address=0.0.0.0
    - --remote-debugging-port=9222
    - --hide-scrollbars
    - --disable-blink-features=AutomationControlled
    - --window-size=1440,900
    labels:
    - runtipi.managed=true
  meilisearch:
    image: getmeili/meilisearch:latest
    user: 1000:1000
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: ${APP_SEED}
    volumes:
    - ${APP_DATA_DIR}/data/meilisearch_data:/meili_data
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
