services:
  server:
    image: ghcr.io/basecamp/once-campfire:1.4.9@sha256:0c50e967c317e2863dbcd16e513f6b814db80d945c487ac047b432b24c29b74b
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data/app:/rails/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${APP_SEED}
      REDIS_URL: redis://redis:6379
      DISABLE_SSL: 'true'
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
    depends_on:
    - redis
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
  redis:
    image: redis:7-alpine@sha256:ee64a64eaab618d88051c3ade8f6352d11531fcf79d9a4818b9b183d8c1d18ba
    user: 1000:1000
    command: redis-server --save 60 1 --save 300 10 --save 900 100 --appendonly yes --loglevel warning
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
