services:
  db:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=db_dev
    - MYSQL_LOG_CONSOLE=true
    - MARIADB_AUTO_UPGRADE=1
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    labels:
    - runtipi.managed=true
    restart: unless-stopped
  memcached:
    image: memcached:latest
    entrypoint: memcached -m 256
    labels:
    - runtipi.managed=true
    restart: unless-stopped
  seafile:
    image: seafileltd/seafile-mc:latest
    volumes:
    - ${APP_DATA_DIR}/data/seafile-data:/shared
    environment:
    - DB_HOST=db
    - DB_ROOT_PASSWD=db_dev
    - SEAFILE_MYSQL_DB_HOST=db
    - SEAFILE_MYSQL_DB_PORT=3306
    - SEAFILE_MYSQL_DB_USER=root
    - SEAFILE_MYSQL_DB_PASSWORD=db_dev
    - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=db_dev
    - SEAFILE_MYSQL_DB_CCNET_DB_NAME=ccnet_db
    - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
    - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=seahub_db
    - JWT_PRIVATE_KEY=${APP_SEED}
    - INIT_SEAFILE_ADMIN_EMAIL=umbrel
    - INIT_SEAFILE_ADMIN_PASSWORD=${APP_PASSWORD}
    - SEAFILE_SERVER_LETSENCRYPT=false
    - SEAFILE_SERVER_HOSTNAME=localhost:8920
    - SEAFILE_SERVER_PROTOCOL=http
    - SITE_ROOT=/
    - ENABLE_SEADOC=true
    - SEADOC_SERVER_URL=http://localhost:8921
    - CACHE_PROVIDER=memcached
    - MEMCACHED_HOST=memcached
    - MEMCACHED_PORT=11211
    depends_on:
    - db
    - memcached
    labels:
    - runtipi.managed=true
    restart: unless-stopped
    x-runtipi:
      internal_port: 80
      is_main: true
  seadoc:
    image: seafileltd/sdoc-server:3.0.2-testing
    volumes:
    - ${APP_DATA_DIR}/data/seadoc-data:/shared
    ports:
    - 8921:80
    environment:
    - DB_HOST=db
    - DB_USER=root
    - DB_PASSWORD=db_dev
    - DB_NAME=seahub_db
    - JWT_PRIVATE_KEY=${APP_SEED}
    - SEAHUB_SERVICE_URL=http://seafile
    depends_on:
    - db
    labels:
    - runtipi.managed=true
    restart: unless-stopped
x-runtipi:
  schema_version: 2
