services:
  web:
    image: wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      powersync_setup:
        condition: service_completed_successfully
    environment:
      SECRET_KEY: ${APP_SEED}
      CSRF_TRUSTED_ORIGINS: ${APP_PROTOCOL:-http}://${APP_DOMAIN}:${APP_WGER_PORT},${APP_PROTOCOL:-http}://${APP_DOMAIN}:${APP_WGER_PORT},${APP_WGER_LOCAL_URLS}
      SITE_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}:${APP_WGER_PORT}
      MEDIA_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}:${APP_WGER_PORT}/media/
      PS_DATABASE_URI: postgres://wger:wger@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:${APP_SEED}@db:5432/wger
      POWERSYNC_URL_PATH: ps
    volumes:
    - ${APP_DATA_DIR}/data/static:/home/wger/static
    - ${APP_DATA_DIR}/data/media:/home/wger/media
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  powersync_setup:
    image: wger/server:latest
    command: ./manage.py setup-powersync-storage
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${APP_SEED}
      PS_DATABASE_URI: postgres://wger:wger@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:${APP_SEED}@db:5432/wger
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  powersync:
    image: journeyapps/powersync-service:latest
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
      powersync_setup:
        condition: service_completed_successfully
    command:
    - start
    - -r
    - unified
    environment:
      POWERSYNC_CONFIG_PATH: /config/powersync.yaml
      PS_JWKS_URL: http://web:8000/api/v2/powersync-keys
      PS_DATABASE_URI: postgres://wger:wger@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:${APP_SEED}@db:5432/wger
      PS_PORT: 8080
    volumes:
    - ${APP_DATA_DIR}/powersync.yaml:/config/powersync.yaml:ro
    - ${APP_DATA_DIR}/sync_rules.yaml:/config/sync_rules.yaml:ro
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  nginx:
    image: nginx:latest
    depends_on:
    - web
    - powersync
    volumes:
    - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ${APP_DATA_DIR}/data/static:/wger/static:ro
    - ${APP_DATA_DIR}/data/media:/wger/media:ro
    healthcheck:
      test:
      - CMD
      - wget
      - --quiet
      - --tries=1
      - --spider
      - http://127.0.0.1:80/
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
  db:
    image: postgres:latest
    shm_size: 256mb
    environment:
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: wger
      POSTGRES_DB: wger
      TZ: Europe/Berlin
    volumes:
    - ${APP_DATA_DIR}/data/postgres-data:/var/lib/postgresql/data/
    command:
    - postgres
    - -c
    - wal_level=logical
    - -c
    - shared_buffers=256MB
    - -c
    - effective_cache_size=768MB
    - -c
    - work_mem=8MB
    - -c
    - random_page_cost=1.1
    - -c
    - max_connections=30
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  cache:
    image: redis:latest
    volumes:
    - ${APP_DATA_DIR}/data/redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  celery_worker:
    image: wger/server:latest
    command: /start-worker
    environment:
      SECRET_KEY: ${APP_SEED}
      PS_DATABASE_URI: postgres://wger:wger@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:${APP_SEED}@db:5432/wger
    volumes:
    - ${APP_DATA_DIR}/data/media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  celery_beat:
    image: wger/server:latest
    command: /start-beat
    environment:
      SECRET_KEY: ${APP_SEED}
      PS_DATABASE_URI: postgres://wger:wger@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:${APP_SEED}@db:5432/wger
    volumes:
    - ${APP_DATA_DIR}/data/celery-beat:${APP_DATA_DIR}/beat/
    depends_on:
      celery_worker:
        condition: service_healthy
    restart: unless-stopped
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
