services:
  web:
    image: germannewsmaker/myspeed:1.0.9@sha256:3a3e774b3f78d930a5a962d625b99bcb3d71730bfeb4a6b93e04fd38cfe7d9a9
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/myspeed:/myspeed/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 5216
      is_main: true
x-runtipi:
  schema_version: 2
