services:
  web:
    image: corentinth/enclosed:1.16.0-rootless@sha256:0631baee489b974cf16ffe3884c814e7bcc75df7bd36662b8ded76443b768d06
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data:/app/.data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8787
      is_main: true
x-runtipi:
  schema_version: 2
