services:
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    restart: unless-stopped
    environment:
      PUBLIC_SERVER_URL: http://server:8000
      ORIGIN: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      BODY_SIZE_LIMIT: Infinity
    depends_on:
    - server
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
  db:
    image: ghcr.io/baosystems/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: adventure
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data/
    labels:
    - runtipi.managed=true
  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    restart: unless-stopped
    environment:
    - PGHOST=db
    - PGDATABASE=database
    - PGUSER=adventure
    - PGPASSWORD=adventure
    - SECRET_KEY=adventure
    - DJANGO_ADMIN_USERNAME=admin
    - DJANGO_ADMIN_PASSWORD=admin
    - DJANGO_ADMIN_EMAIL=admin@example.com
    - PUBLIC_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
    - CSRF_TRUSTED_ORIGINS=${APP_PROTOCOL:-http}://${APP_DOMAIN}
    - DEBUG=False
    - FRONTEND_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
    ports:
    - 8016:80
    depends_on:
    - db
    volumes:
    - ${APP_DATA_DIR}/data/app:/code/media/
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
