services:
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    restart: on-failure
    environment:
      PUBLIC_SERVER_URL: http://server:8000
      ORIGIN: http://localhost:8015
      BODY_SIZE_LIMIT: Infinity
    depends_on:
    - server
    x-runtipi:
      internal_port: 3000
      is_main: true
  db:
    image: ghcr.io/baosystems/postgis:latest
    restart: on-failure
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: adventure
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data/
  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    restart: on-failure
    environment:
    - PGHOST=adventurelog_db_1
    - PGDATABASE=database
    - PGUSER=adventure
    - PGPASSWORD=adventure
    - SECRET_KEY=adventure
    - DJANGO_ADMIN_USERNAME=admin
    - DJANGO_ADMIN_PASSWORD=admin
    - DJANGO_ADMIN_EMAIL=admin@example.com
    - PUBLIC_URL=http://localhost:8016
    - CSRF_TRUSTED_ORIGINS=http://localhost:8015
    - DEBUG=False
    - FRONTEND_URL=http://localhost:8015
    ports:
    - 8016:80
    depends_on:
    - db
    volumes:
    - ${APP_DATA_DIR}/data/app:/code/media/
x-runtipi:
  schema_version: 2
