services:
  migrate:
    image: ghcr.io/kanbn/kan-migrate:latest
    environment:
      POSTGRES_URL: postgresql://kanuser:kanpassword@db:5432/kan?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  server:
    image: ghcr.io/kanbn/kan:latest
    environment:
      NEXT_PUBLIC_BASE_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      BETTER_AUTH_SECRET: ${APP_SEED}
      POSTGRES_URL: postgresql://kanuser:kanpassword@db:5432/kan?sslmode=disable
      NEXT_PUBLIC_ALLOW_CREDENTIALS: 'true'
    depends_on:
    - db
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kan
      POSTGRES_USER: kanuser
      POSTGRES_PASSWORD: kanpassword
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U kanuser -d kan
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
