services:
  app:
    image: dennysubke/seedtool:2.3.0@sha256:ab5a3bd42d7d4d0afc9c77ea9448e5d34244b66d7064eac75247601934fb90cc
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
