services:
  web:
    image: ghcr.io/fccview/jotty:1.26.0@sha256:44b05273db46129ad2f8fc599ce7a8809a4fb8edbcb16bc651eef7ae1f7a9f5f
    user: 1000:1000
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/app:/app/data
    - ${APP_DATA_DIR}/data/config:/app/config
    - ${APP_DATA_DIR}/data/cache:/app/.next/cache
    environment:
    - NODE_ENV=production
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
