services:
  api_web:
    image: toshimoto821/toshi-moto-api:1.8.4@sha256:750927ef2d0b0bbcffcbb57632d861e567a8b7243381c0285b2b2660dc31244a
    restart: unless-stopped
    stop_grace_period: 1m
    user: 1000:1000
    depends_on:
    - mongodb
    environment:
      PORT: 8121
      MONGODB_URI: mongodb://mongodb:27017/toshi-moto
    labels:
    - runtipi.managed=true
  web:
    image: toshimoto821/toshi-moto:1.37.3@sha256:e2d7270473dda60c34afac9ed28b267540fd4ca0d6aabf12fa37a7d0c597634e
    restart: unless-stopped
    user: 1000:1000
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - api_web
    environment:
      PORT: 8021
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8021
      is_main: true
  mongodb:
    image: mongo:8.0.10@sha256:15fb53a5160ebabff5ecade8f8b5d48721b68ea190957a7f35b5b38e8340e62b
    stop_grace_period: 1m
    user: 1000:1000
    command: mongod --noauth
    volumes:
    - ${APP_DATA_DIR}/data/db:/data/db
    labels:
    - runtipi.managed=true
    restart: unless-stopped
x-runtipi:
  schema_version: 2
