services:
  api_web:
    image: toshimoto821/toshi-moto-api:1.8.4
    restart: unless-stopped
    stop_grace_period: 1m
    depends_on:
    - mongodb
    environment:
      PORT: 8121
      MONGODB_URI: mongodb://mongodb:27017/toshi-moto
    labels:
    - runtipi.managed=true
  web:
    image: toshimoto821/toshi-moto:1.37.3
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - api_web
    environment:
      PORT: 8021
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8021
      is_main: true
  mongodb:
    image: mongo:latest
    stop_grace_period: 1m
    command: mongod --noauth
    volumes:
    - ${APP_DATA_DIR}/data/db:/data/db
    labels:
    - runtipi.managed=true
    restart: unless-stopped
x-runtipi:
  schema_version: 2
