services:
  homepage:
    image: loficafe/static-web-server-samba:1.0.1@sha256:783667f052d9535bb75946ff9bc807989b041e25437ef10c30b291589d041e6e
    restart: unless-stopped
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data/samba/smb.conf:/public/smb.conf:ro
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
  server:
    image: dockurr/samba:4.23.5@sha256:63428d1cb6c1ace60cfa782c1d6c9e4b3686044fc47600c97055e6b62e9bb5fa
    restart: unless-stopped
    environment:
      USER: umbrel
      PASS: ${APP_PASSWORD}
      UID: 1000
      GID: 1000
    ports:
    - 446:445
    volumes:
    - ${APP_DATA_DIR}/data/samba/smb.conf:/etc/samba/smb.conf
    - ${RUNTIPI_MEDIA_DIR}/:/storage
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
