services:
  server:
    image: ghcr.io/thomiceli/opengist:latest
    restart: unless-stopped
    ports:
    - 2224:2224
    volumes:
    - ${APP_DATA_DIR}/data:/opengist
    environment:
      OG_SSH_PORT: '2224'
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 6157
      is_main: true
x-runtipi:
  schema_version: 2
