services:
  web:
    image: ghcr.io/besoeasy/gupt:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
