services:
  web:
    image: ghcr.io/besoeasy/gupt:2.80.4@sha256:ab88455d212a20250d5422ad371160756be5c35ffded633d1689f3538096d010
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
