services:
  ui:
    image: joni1802/ts3-manager:latest
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      JWT_SECRET: $APP_SEED
    x-runtipi:
      internal_port: 8080
      is_main: true
  server:
    image: teamspeak:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - 9987:9987/udp
    - 10011:10011
    - 30033:30033
    volumes:
    - ${APP_DATA_DIR}/data:/var/ts3server
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_SERVERADMIN_PASSWORD: $APP_PASSWORD
x-runtipi:
  schema_version: 2
