services:
  web:
    image: ipfspodcasting/podcastnode:v0.6
    init: true
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
    - 4001:4001
    volumes:
    - ${APP_DATA_DIR}/ipfs:/ipfs-podcasting/ipfs
    - ${APP_DATA_DIR}/cfg:/ipfs-podcasting/cfg
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8675
      is_main: true
x-runtipi:
  schema_version: 2
