services:
  web:
    image: ghcr.io/gandlafbtc/nutstash-wallet:0.1.12
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
