services:
  web:
    image: ghcr.io/gandlafbtc/nutstash-wallet:0.1.10@sha256:8a585c4a6545e68e9a1c8fcf2a0a15ef401ad040accf925234451fe1b838d180
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
