services:
  web:
    image: ghcr.io/richardr1126/openreader:4.4.0@sha256:2e3ec184dac71082646995a17309add008405827d81a020fb6d264360f7c1a49
    user: 1000:1000
    environment:
    - API_BASE=http://kokoro_web_1:8880/v1
    - BASE_URL=http://localhost:3391
    - AUTH_SECRET=${APP_SEED}
    - AUTH_TRUSTED_ORIGINS=http://localhost:3391,http://localhost:3391,http://*.ts.net:3391,https://*.ts.net:3391,${APP_OPENREADER_LOCAL_URLS}
    - USE_ANONYMOUS_AUTH_SESSIONS=true
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/docstore:/app/docstore
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3003
      is_main: true
x-runtipi:
  schema_version: 2
