services:
  web:
    image: linuxserver/pyload-ng:0.5.0@sha256:0ef3e1d15183eb7f517742afe2f75b42c1d58e14640f8d5741f6e88d2d7b9ab5
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
