services:
  server:
    image: ghcr.io/papra-hq/papra:latest
    user: 1000:1000
    restart: on-failure
    environment:
    - AUTH_SECRET=${APP_SEED}
    - APP_BASE_URL=http://localhost:8112
    volumes:
    - ${APP_DATA_DIR}/data:/app/app-data
    x-runtipi:
      internal_port: 1221
      is_main: true
x-runtipi:
  schema_version: 2
