services:
  ollama:
    image: ollama/ollama:latest
    environment:
      OLLAMA_ORIGINS: '*'
      OLLAMA_CONTEXT_LENGTH: 8192
    volumes:
    - ${APP_DATA_DIR}/data:/root/.ollama
    restart: on-failure
    x-runtipi:
      internal_port: 11434
      is_main: true
x-runtipi:
  schema_version: 2
