services:
  web:
    image: ghcr.io/matt8707/ha-fusion:latest
    restart: unless-stopped
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data/fusion:/app/data
    environment:
      HASS_URL: http://localhost:8123
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 5050
      is_main: true
x-runtipi:
  schema_version: 2
