services:
  app:
    image: ghcr.io/besoeasy/zeronote:latest
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
    - NODE_ENV=production
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
