services:
  app:
    image: ghcr.io/besoeasy/zeronote:1.0.12@sha256:208586649fcf38a86b73f2b7ed5888d71faac38729fd00c5a793ab90b09ecf2f
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
    - NODE_ENV=production
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
