services:
  web:
    image: datarhei/restreamer:latest
    environment:
    - PUID=1000
    - PGID=1000
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/config:/core/config
    - ${APP_DATA_DIR}/data:/core/data
    ports:
    - 8181:8181
    - 1935:1935
    - 1936:1936
    - 6000:6000/udp
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
