services:
  web:
    image: ghcr.io/mckaywrigley/chatbot-ui:main@sha256:569dffe6043136f03de86bde38453a58d05150f29476239dc1da4ce2573b4101
    labels:
    - runtipi.managed=true
    restart: unless-stopped
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
