services:
  server:
    image: ghcr.io/bisq-network/bisq2-api:latest
    restart: unless-stopped
    stop_grace_period: 1m
    mem_limit: 2g
    volumes:
    - ${APP_DATA_DIR}/data:/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8091
      is_main: true
  web:
    image: ghcr.io/bisq-network/bisq2-api-web-ui:latest
    restart: unless-stopped
    network_mode: service:server
    volumes:
    - ${APP_DATA_DIR}/data:/data:ro
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
