services:
  web:
    image: ghcr.io/vert-sh/vert:latest
    restart: unless-stopped
    environment:
      PUB_HOSTNAME: http://localhost:3884
      PUB_VERTD_URL: http://localhost:3884
      PUB_ENV: production
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
