services:
  app:
    image: ghcr.io/egzola/bitboard:1.0.0
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      PORT: 3711
    volumes:
    - ${APP_DATA_DIR}/data:/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3711
      is_main: true
x-runtipi:
  schema_version: 2
