services:
  app:
    image: influxdb:latest
    user: 1000:1000
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/data:/var/lib/influxdb2
    - ${APP_DATA_DIR}/data/config:/etc/influxdb2
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8086
      is_main: true
x-runtipi:
  schema_version: 2
