services:
  web:
    image: ghcr.io/thelounge/thelounge:latest
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data:/var/opt/thelounge
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 9000
      is_main: true
x-runtipi:
  schema_version: 2
