services:
  web:
    image: rotki/rotki:latest
    restart: unless-stopped
    stop_grace_period: 1m
    init: true
    volumes:
    - ${APP_DATA_DIR}/data/data:/data
    - ${APP_DATA_DIR}/data/logs:/logs
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
