services:
  web:
    image: ceramicwhite/libreddit:latest
    restart: unless-stopped
    stop_grace_period: 1m
    init: true
    environment:
      PORT: 7420
    healthcheck:
      disable: true
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 7420
      is_main: true
x-runtipi:
  schema_version: 2
