services:
  web:
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.17.2@sha256:d4351369984d4a9e2a49ac59736f6490856a7ea11f7790040746d21496967010
    shm_size: 128mb
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/storage:/media/frigate
    ports:
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${APP_PASSWORD}
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8971
      is_main: true
x-runtipi:
  schema_version: 2
