services:
  web:
    image: dennysubke/torbrowser:latest
    restart: on-failure
    environment:
    - DARK_MODE=1
    - WEB_AUDIO=1
    volumes:
    - ${APP_DATA_DIR}/config:/config
    x-runtipi:
      internal_port: 5800
      is_main: true
x-runtipi:
  schema_version: 2
