services:
  web:
    image: getumbrel/umbrel-nostr-relay:latest
    user: 1000:1000
    restart: on-failure
    environment:
      RELAY_HOST: nostr-relay_relay_1
      RELAY_PORT: '8080'
      RELAY_PROXY_HOST: nostr-relay_relay-proxy_1
      RELAY_PROXY_PORT: '80'
    x-runtipi:
      internal_port: 3000
      is_main: true
  relay:
    image: getumbrel/nostr-rs-relay:0.8.1
    user: 1000:1000
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/relay/config.toml:/app/config.toml
    - ${APP_DATA_DIR}/data/relay/db:/app/db
  relay-proxy:
    image: getumbrel/umbrel-nostr-relay-proxy:v1.1.0
    user: 1000:1000
    restart: on-failure
    environment:
      RELAY_HOST: nostr-relay_relay_1
      RELAY_PORT: '8080'
    volumes:
    - ${APP_DATA_DIR}/data/relay-proxy:/app/data
    depends_on:
    - relay
x-runtipi:
  schema_version: 2
