services:
  web:
    image: ghcr.io/ersatztv/legacy:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/transcode:/transcode
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/media:ro
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8409
      is_main: true
x-runtipi:
  schema_version: 2
