services:
  web:
    image: ghcr.io/ersatztv/legacy:latest
    restart: on-failure
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/transcode:/transcode
    - ${RUNTIPI_MEDIA_DIR}/downloads/:/media:ro
    x-runtipi:
      internal_port: 8409
      is_main: true
x-runtipi:
  schema_version: 2
