services:
  app:
    image: ghcr.io/anomalyco/opencode:1.18.17@sha256:c472d1c6c575b86ccc44ff639a1bb2093fd75ab7095be46f8b3c0a04c299fd60
    command:
    - serve
    - --hostname
    - 0.0.0.0
    - --port
    - '4096'
    restart: unless-stopped
    user: 1000:1000
    environment:
      HOME: /home/opencode
    volumes:
    - ${APP_DATA_DIR}/data/opencode:/home/opencode/
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 4096
      is_main: true
x-runtipi:
  schema_version: 2
