services:
  app:
    image: ghcr.io/anomalyco/opencode:latest
    command:
    - serve
    - --hostname
    - 0.0.0.0
    - --port
    - '4096'
    restart: unless-stopped
    user: 1000:1000
    environment:
      HOME: /home/opencode
    volumes:
    - ${APP_DATA_DIR}/data/opencode:/home/opencode/
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 4096
      is_main: true
x-runtipi:
  schema_version: 2
