services:
  plausible_db:
    image: postgres:latest
    restart: on-failure
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=postgres
  plausible_events_db:
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    user: 1000:1000
    volumes:
    - ${APP_DATA_DIR}/event-data:/var/lib/clickhouse
    - ${APP_DATA_DIR}/event-logs:/var/log/clickhouse-server
    - ${APP_DATA_DIR}/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
    - ${APP_DATA_DIR}/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1
  plausible:
    image: ghcr.io/plausible/community-edition:latest
    restart: on-failure
    user: 1000:1000
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
    - plausible_db
    - plausible_events_db
    environment:
    - BASE_URL=http://localhost:9093
    - SECRET_KEY_BASE=${APP_SEED}
    - TOTP_VAULT_KEY=${APP_PLAUSIBLE_VAULT_KEY}
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
