services:
  web:
    image: voidic/dtan-server:v0.2.0@sha256:8ffce76cc82d00fbe8571bedfd6699fbd91e97d89ff5e6cbc32dbf03b9d58ad1
    restart: unless-stopped
    environment:
    - RUST_LOG=info
    volumes:
    - ${APP_DATA_DIR}/data/app:/app/data
    - ${APP_DATA_DIR}/data/config/config.yml:/app/config.yml
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
x-runtipi:
  schema_version: 2
