services:
  app:
    image: ghcr.io/umami-software/umami:latest
    user: 1001:1001
    restart: on-failure
    stop_grace_period: 1m
    environment:
      DATABASE_URL: postgresql://umami:umami@umami_db_1:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SEED}
    depends_on:
    - db
    x-runtipi:
      internal_port: 3000
      is_main: true
  db:
    image: postgres:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
x-runtipi:
  schema_version: 2
