services:
  web:
    image: ghcr.io/alam00000/bentopdf:v2.8.7@sha256:165113f4579cc61ea353ad0597ed510cc2101ef879ec5e91875a3df0c0b219a0
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
