services:
  web:
    image: ghcr.io/alam00000/bentopdf:latest
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
