services:
  web:
    image: stnsmith/fossflow:master-b69fc2e@sha256:c0813b19a9c8a3b8d13901de0e35edf7d9300ae8327a905ff520239d5624dafc
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/diagrams:/data/diagrams
    environment:
    - NODE_ENV=production
    - ENABLE_SERVER_STORAGE=true
    - STORAGE_PATH=/data/diagrams
    - ENABLE_GIT_BACKUP=false
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
