services:
  web:
    image: recksato/robosats-client:v0.8.4-alpha@sha256:85bf9ace2eafbcd7c5c61f62d81423aea63ddf08375f5cbe1090392bb49e92f8
    restart: unless-stopped
    stop_grace_period: 1m
    init: true
    environment:
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 12596
      is_main: true
x-runtipi:
  schema_version: 2
