services:
  web:
    image: calvadev/shopstr:latest
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 3000
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
