services:
  web:
    image: calvadev/shopstr:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      PORT: 3000
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
x-runtipi:
  schema_version: 2
