services:
  server:
    image: stalwartlabs/stalwart:latest
    user: 1000:1000
    environment:
    - STALWART_RECOVERY_ADMIN=admin:${APP_PASSWORD}
    - STALWART_PUBLIC_URL=http://localhost:8745
    ports:
    - 10443:443
    - '10025:25'
    - 10465:465
    - 10587:587
    - 10143:143
    - 10993:993
    - 14190:4190
    - 10110:110
    - 10995:995
    volumes:
    - ${APP_DATA_DIR}/data/etc:/etc/stalwart
    - ${APP_DATA_DIR}/data/server:/var/lib/stalwart
    restart: on-failure
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
