services:
  server:
    image: twentycrm/twenty:latest
    volumes:
    - ${APP_DATA_DIR}/data/server-local-data:/app/packages/twenty-server/.local-storage
    - ${APP_DATA_DIR}/data/docker-data:/app/docker-data
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      FRONT_AUTO_BASE_URL: 'true'
      REDIS_URL: redis://redis:6379
      APP_SECRET: 2Gn5puuVCH0SI386E9RqOqHm0hGIAyrB
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 120s
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3000
      is_main: true
  worker:
    image: twentycrm/twenty:latest
    volumes:
    - ${APP_DATA_DIR}/data/server-local-data:/app/packages/twenty-server/.local-storage
    command:
    - yarn
    - worker:prod
    environment:
      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/default
      SERVER_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      REDIS_URL: redis://redis:6379
      DISABLE_DB_MIGRATIONS: 'true'
      DISABLE_CRON_JOBS_REGISTRATION: 'true'
      APP_SECRET: 2Gn5puuVCH0SI386E9RqOqHm0hGIAyrB
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  db:
    image: postgres:latest
    volumes:
    - ${APP_DATA_DIR}/data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost -d postgres
      interval: 10s
      timeout: 30s
      retries: 10
    restart: unless-stopped
    labels:
    - runtipi.managed=true
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
