services:
  app:
    image: ghcr.io/besoeasy/l-town:latest
    restart: unless-stopped
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 30300
      is_main: true
x-runtipi:
  schema_version: 2
