services:
  web:
    image: ghcr.io/mainsail-crew/mainsail:v2.18.2@sha256:7351715acdda0d893c759b96c54d8e772321300863e622db59a7d8d29b69976f
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/config.json:/usr/share/nginx/html/config.json:ro
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
