services:
  server:
    image: awinterstein/habitica-server:latest
    restart: on-failure
    command: 'sh -c "perl -0pi -e ''s/upgradeInsecureRequests: IS_PROD \\? \\[\\] : null,?/upgradeInsecureRequests: null/g'' /var/lib/habitica/website/server/middlewares/index.js /var/lib/habitica/website/transpiled-babel/middlewares/index.js && printenv | grep -v ''no_proxy'' >> /etc/environment && /etc/init.d/cron start && node /var/lib/habitica/website/transpiled-babel/index.js"'
    depends_on:
    - mongo
    environment:
    - NODE_DB_URI=mongodb://habitica_mongo_1/habitica
    - BASE_URL=http://localhost:3944
    - INVITE_ONLY=false
    x-runtipi:
      internal_port: 3000
      is_main: true
  mongo:
    image: mongo:latest
    restart: on-failure
    command:
    - --replSet
    - rs
    - --bind_ip_all
    - --port
    - '27017'
    healthcheck:
      test: 'echo "try { rs.status() } catch (err) { rs.initiate({ _id: ''rs'', members: [{ _id: 0, host: ''habitica_mongo_1:27017'' }] }) }" | mongosh --port 27017 --quiet

        '
      interval: 10s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
    - ${APP_DATA_DIR}/data/db:/data/db:rw
    - ${APP_DATA_DIR}/data/dbconf:/data/configdb
x-runtipi:
  schema_version: 2
