services:
  server:
    image: ghcr.io/glasshome/dash:1.0.0@sha256:a00a5537447b1df187d6516a722de7913ca2514a5610d4a825010df09777663a
    restart: unless-stopped
    environment:
      PORT: 3123
      DATA_DIR: /data
    volumes:
    - ${APP_DATA_DIR}/data:/data
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 3123
      is_main: true
x-runtipi:
  schema_version: 2
