services:
  app:
    image: ghcr.io/netbirdio/netbird:0.77.0-rootless@sha256:22a3b8b6aedf8748505dcd0dd4ab762cf469f7652fc2f1265975cdf02201bef8
    restart: unless-stopped
    user: 1000:1000
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
    network_mode: host
    volumes:
    - ${APP_DATA_DIR}/data/app_data:/var/lib/netbird:rw
    labels:
    - runtipi.managed=true
  web:
    image: nginx:1.27@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/www:/usr/share/nginx/html:ro
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
