services:
  web:
    image: dennysubke/cobalt:latest
    read_only: true
    restart: unless-stopped
    ports:
    - 9013:9000
    environment:
      API_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}/
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 9001
      is_main: true
x-runtipi:
  schema_version: 2
