services:
  web:
    image: ghcr.io/fuzzygrim/yamtrack:latest
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    depends_on:
    - redis
    environment:
      SECRET: ${APP_SEED}
      REDIS_URL: redis://redis:6379
    volumes:
    - ${APP_DATA_DIR}/data/db:/yamtrack/db:rw
    labels:
    - runtipi.managed=true
    x-runtipi:
      internal_port: 8000
      is_main: true
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data:rw
    labels:
    - runtipi.managed=true
x-runtipi:
  schema_version: 2
